### ISSUE TITLE
Various changes to filter option

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#100]
I was in communication with O today and there are a few things thiat should be changes on filter view:
- description of sequence length -> we are not counting in 'words', but in characters now because that is linguistically a bit more satisfying (so I changed the max. value to 300 and default to 50). 
- number of results: I think we can remove this filter completely. It dates back to the time when we organized our display in a table format per segment, but we now changed to a different system and this doesn't really apply anymore. If one is overwhelmed by the results / hunting for raw quotes, 'filter by co-occurence' might work much better.

**Comment by ayya-vimala** [comment]
I can take this and push that later today.

**Comment by ayya-vimala** [comment]
`    if (this.language == 'chinese') {
      this.quoteLength = 5;
    }`

Is this still valid as a setup in table-view? I guess not. I will remove it.

**Comment by sebastian-nehrdich** [comment]
Yes this can go.
The problem is that we need different defaults for each language. Length is
now based on character count and 50 characters is somewhat a nice value for
Tibetan, but Chinese needs a very different default.
If it's possible, could you change the default length cutoff for Chinese to
7? That would be great!

**Comment by ayya-vimala** [comment]
Okay, PR created and after you merge this you can delete the branch also, otherwise we get millions of branches.
I also removed some redundant code in relation to max-results.
