### ISSUE TITLE
Changes to the JSON layout

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#102]
There are a few things about the JSON layout that are not ideal and since we are now moving things to an API/DB, I think it's a good time to clean up a bit.
- I would like to seperate root segments and parallels into two lists. So each JSON has two main lists: one is collecting the root-segments and the other the parallels. this is more close to the layout of the DB that we are aiming at as far as I can see. 
- I would like to add an unique identifier to each parallel as TrebuhD suggested on gitter.  My question here is: Can we use alphanumerical schemes or are we bound to numbers db-wise? or whatever the 'best practice' for such identifiers in this case is (I really don't know). My first suggestion for a schme would be to just take the name of the root text and add incrementing numbers to it, so we get things links T06TD4021ID0,T06TD4021ID1 etc. - this might look a bit similar to the segment identifiers I got to admit. Don't know if that's a problem though... 
- in this way, each quote will only appear once in the JSON and it will have an unique identifier, so we solve some of the problems that we experience at the moment.

**Comment by sebastian-nehrdich** [comment]
The first batch of the new jsons is now on the server. They consist of two lists, one containing the root segments, the other one the parallels. I added an unique id-tag to each parallel. Also there *should* be no duplicates anymore among the parallels, but I haven't yet debugged this carefully. 
I think in the DB we don't need to collect the segment text for each parallel (collected under 'parsegment'). This data we can query from the collection with the root segments.

**Comment by ayya-vimala** [comment]
The parsegment is indeed not necessary so that can reduce the size of the files further. But I'm missing some values that you mentioned earlier:

> root_position_beg
> root_position_end
> postion

Instead there is head_beg and head_end.

Also, I think the language is not needed on the each one of the segments (only necessary for the parallels). This can be deduced from the file it is in and added in the database that way.

**Comment by sebastian-nehrdich** [comment]
The updated JSONS are now on the server. I made the previously discussed changes. Please be aware that the position-value in the root-segment doesn't rise incrementally but has larger gaps, because it reflects the position of the first token on the global index for the entire canon. The advantage is that this value is globally unique.

**Comment by ayya-vimala** [comment]
Okay. Looks good. The only thing I think is a bit redundant is the language on the segments themselves: these are tibetan files so when loading the system will know that they are in the tib folder. But that won't make a huge difference.

**Comment by sebastian-nehrdich** [comment]
yes I think it dates back to the time when we had multiple languages in one json file... 
I will now make a new branch and modify our website so it can read the new json files. Once that is done I will make a pull request and then close this issue when everything looks good.

**Comment by sebastian-nehrdich** [comment]
@ayya-vimala   loading of the new files is working now, I got it in this branch:  OK loading of the new files is working now, I got in this branch: https://github.com/ayya-vimala/pali-networks/tree/102-load-new-jsons
I hope the naming scheme is right. Number view and loading on the right side (after clicking on a parallel in the middle) are broken now. The last one I wanted to rewrite anyway this days. Should I do a pull request with the state 'as it is' so we keep our efforts in sync or should I fix the right hand side display first?

**Comment by ayya-vimala** [comment]
I would not merge this with master. You can just use it to show things on to Orna and others (of course fix things too for that purpose).
With the database the whole loading will be completely different anyway. If need be, I can look at your code.

**Comment by TrebuhD** [comment]
@sebastian-nehrdich sorry, I almost missed the question here. Please use the `@` sign when mentioning, this way I'll get notified :).

For the IDs, we can use any `1 < n < 255` character sized sequence of these characters:
```
letters a-z (lower or upper case), the digits 0-9 or any of the following punctuation:

characters: _ - : . @ ( ) + , = ; $ ! * ' %
```

**Comment by sebastian-nehrdich** [comment]
@TrebuhD @ayya-vimala I have now uploaded updated jsons to the server. They are to be found under pub/suttas/tib. 
I made some changes so that things become a bit more consistent. The last days and weeks our naming scheme (which was chosen quite ad-hoc as far as I remember) has driven me crazy a few times so I decided to make things more clear (better change it now than never). 
A parallel now looks  like this: 
`
       {
            "score": 52,
            "par_length": 48,
            "id": "T06TD4064E:4439",
            "par_pos_beg": 19511588,
            "par_pos_last": 19511588,
            "root_pos_beg": 27045990,
            "root_pos_end": 27045996,
            "par_offset_beg": 250,
            "par_offset_end": 19,
            "par_segnr": [
                "T04TD3948E:2006_0",
                "T04TD3948E:2008_0"
            ],
            "par_segtext": [
                "slob dpon nyid kyis mdzad pa'i ga las 'jigs med dang / slob dpon zla grags kyis mdzad pa'i tshig don gsal ba dang / slob dpon bha bya snang bral gyis mdzad pa'i shes rab sgron ma dang / gnas brtan buddha p'a li tas mdzad pa'i buddha p'a li ta dang / slob dpon blo brtan gyis mdzad @281a * //",
                "pa dang ; slob dpon gu na ma ti dang / slob dpon gu na shr'i dang / a'ats'a rya gu na da tas mdzad pa rnams so //"
            ],
            "par_string": "slob dpon blo brtan gyis mdzad @281a * //pa dang ; slob dpon ",
            "root_string": "slob dpon blo brtan gyis ",
            "root_offset_beg": 21,
            "root_offset_end": 45,
            "root_segnr": [
                "T06TD4064E:1362_1"
            ],
            "co-occ": 1
        }
`
What has changed?
- use of underscores is now consistent
- parsegment -> par_segtext (for me it was always a pain to distinguish between our use of the term segment and segmentnr)
- position -> pos 
- added root_string and par_string 
in the root-entries:
- segmentnr -> segnr
- segment -> segtext 

As we discussed before, the lang-tag in the root-entries can be dropped since we can deduce that information from the segnr-field.

**Comment by ayya-vimala** [comment]
Good to have it consistent. Yes, I found that difficult at times too.
By the looks of it, probability has now become `score` as well.

**Comment by ayya-vimala** [comment]
As discussed, the jsons can change to:
* No language tags in the segments
* No id in the parallels
* score = probability
* par_segtext, par_string and root_string do not need to be loaded into the database
* par_pos_beg and _end etc. can be used for sorting purposes and Sebastian will make sure these values are correct.

**Comment by sebastian-nehrdich** [comment]
almost! Except par_string and root_string will need to be stored in the DB
as well for the time being because they will contain markup and are not
identical with our segtext-data.
In future I hope I can exchange them with some kind of word alignment data
in numerical format, but I haven't explored the options regarding that yet.

**Comment by ayya-vimala** [comment]
I have uploaded a fix for your 102 branch so it shows the loading and gives a message when it cannot find a file. I have not uploaded to server yet. It now only works locally until you block out those lines in webpack
