### ISSUE TITLE
Routing does not work properly for texts in URL

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#119]
#### Bug Description
When typing a text in the URL as a parameter, it tries to find it in the wrong place.

#### Steps To Reproduce:

1. Go to 'tibetan'
2. Change URL manually to tibetan/T06TD4021E
3. See error message in console. It tries to find the file in `tibetan/suttas/tib/T06TD4021E` and not in `/suttas/tib/T06TD4021E`
 
#### Expected behaviour
Whether typed in the browser or with a link from elsewhere, the file should be found and loaded. It should also be loaded when found in the dropdown menu at the top.

**Comment by ayya-vimala** [comment]
Something like http://buddhist-db.de/tibetan/T06TD4021E does not work.

**Comment by TrebuhD** [comment]
PR: https://github.com/ayya-vimala/pali-networks/pull/124. For some reason I can't connect the issue there.

**Comment by ayya-vimala** [comment]
I tested this locally and it works fine. Thanks.
But somehow when I do the same on Sebastian's branch it does not ... also when trying to merge master into that.

The good news is that this also works on the visual charts so when clicking on a text there, it opens that text.

**Comment by sebastian-nehrdich** [comment]
I think my branch needs webpack.config.js and then it should work

**Comment by ayya-vimala** [comment]
I think you're right. Just tied it and locally it works. Will push and upload to server too.
