### ISSUE TITLE
Paris presentation

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#12]
Everything that needs to done before the Paris presentation on 13th July

* change the "Tokyo-code" to show Tengyur<>Kangyur, Kangyur<>Kangyur, and Tengyur<>Tengyur-data.
* get the frontend working for the Buddhist-texts of GRETIL (involving regenerating the GRETIL-data)
* add as many parallel SKT-TIB etexts as possible (on "Tokyo-code")

**Comment by sebastian-nehrdich** [comment]
Orna would like to start preparing for her presentation by the fifth of July, so the Tibetan display should be working until then. I do not see much that is  very problematic at the moment regarding that. Probably the speed of the website (e.h. loading time of the Suttas and the menus which is now already partly fixed) as well as the visualizations (-> Tokyo code) are the biggest remaining issues that we need to work on until then.
