### ISSUE TITLE
Test and fix production build

### ISSUE THREAD

**Issue by TrebuhD** [ayya-vimala/pali-networks#120]
It looks like the changes to `webpack.config.js` (https://github.com/ayya-vimala/pali-networks/commit/4dc45e15b3778f166a53933b8033422b1b5a1779#diff-11e9f7f953edc64ba14b0cc350ae7b9d) broke the production build for some reason. We should investigate and fix.

**Comment by sebastian-nehrdich** [comment]
As I mentioned in gitter I changed now the server setup so the link is under buddhist-db.de/ 
Currently there is one issue with the routing that I observed: If one hits 'reload' while browsing the Tibetan files, 404 is returned for some reason.

**Comment by ayya-vimala** [comment]
Things are working online with the webpack.config.js but for some reason you cannot get the `dist ` folder any more now after running `npm run prod` even though it runs so you cannot actually upload it.

**Comment by ayya-vimala** [comment]
This might be it:

change: 
`build:webpack": "NODE_ENV=production webpack --config webpack.config.prod.js"`

to

`build:webpack": "set NODE_ENV=production && webpack --config webpack.config.prod.js"`

I cannot test right now due to some internet issues but will try later
