### ISSUE TITLE
Setup ArangoDB Collections - Menus

### ISSUE THREAD

**Issue by TrebuhD** [ayya-vimala/pali-networks#125]
#### This ticket is the 2nd part of #107.

Setup the following collections in arangoDB:

MENU-COLLECTIONS:
```
collection: “tengyur”
categories: [T01,T02,T03,T04,T05,T06, etc.]
language: “tib”
```

MENU-CATEGORIES
```
category: T06
language: “tib”
categoryname: "Vijñaptimātra (Mind Only)"
files: ["T06TD4020E","T06TD4021E","T06TD40220E",etc.]
```

The source data for these collections is not yet available. @ayya-vimala @sebastian-nehrdich  can you confirm that? Do you have an idea when the files might become available?

**Comment by ayya-vimala** [comment]
It is there but I will clean it up first and put it in a separate json file ... tomorrow :-)

**Comment by ayya-vimala** [comment]
I have pushed all the menu files that I have here:
https://github.com/ayya-vimala/pali-networks/tree/master/menujsons
They mimic the above structure except for that the files-lists in san-categories.json and chn-categories.json is empty. Please take the corresponding filenames out of the san-files.json and chn-files.json themselves.
If you have any questions, let me know.

**Comment by TrebuhD** [comment]
I'm getting some name conflicts for collection names. They have to be globally unique in the database, but Tengyur and Kangyur are the same in Tibetan and Sanskrit. Can we change their names (append a suffix?) or do you think that might be a problem?

**Comment by ayya-vimala** [comment]
There are a lot of Tengyur and Kangyur texts of the same collections in both languages.
So you would have T01, etc. in both of them.
Maybe we should give them all some other identifier that is unique other than the category/collection names?
For the collection names it does not matter that much. There are just two of them so you could add the language id to that or so.

**Comment by TrebuhD** [comment]
yeah, we can use a primary key like "Kangyur-pli" if you'd like.

**Comment by ayya-vimala** [comment]
:-) There is no Kangyur in pli. But try 'Kangyur-tib' and 'Kangyur-san'.
