### ISSUE TITLE
table-views (formerly known as segment-views) migration to the API (backend)

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#133]
(I will post a description on what kind of data is needed on the frontend from the API as a comment here later once I looked into this more closely).

**Comment by sebastian-nehrdich** [comment]
@TrebuhD For the table-view, we need queries of the following type:
- all parallels for a given text sorted by either:
 1. Position as they occur in the main text (= sort by "root_pos_beg") 
 2. Position as they occur in the parallel text. This key can be constructed by concatting the filename of the quoted text and a padded version of the par_pos_beg key. The filename of the quoted text can be acquired with a regex on the par_segnr (everything before the ":" is the filename). if the par_segnr key is "T06TD4023E:8" and the par_pos_beg key is 25204623, the resulting alphanumerical key for this sorting method would be "T06TD4023E0025204623". the padding of the position number with zeros is just to make sure that we keep the order also for smaller numbers. The reason why we add the textname in front of the number is because in this way, the order is guaranteed to be according to the catalog of the Tibetan/Chinese/Pāli canon). 
3. By length (key = par_length) starting with longest 
4. By length starting with shortest 
- I have already implemented these sorting strategies on the JSON data in Javascript, so for a quick reference this is what is happening here between line 67 and 95: https://github.com/ayya-vimala/pali-networks/blob/102-load-new-jsons/src/views/options/segment-view.js
- We would  need to fill in the corresponding seg_text-data for the root and the parallel so we can reconstruct the original text.
- linked to the previous point: It would be actually great to receive the seg_texts items for both root and parallel from the database by querying for strings that are in the range between their first and last segment_nr (so first and last item of "par_segnr" and "root_segnr").  We could use the "position" key in the root_segnr collection for this because that key guarantees the order of the elements.  
- I wonder if it is possible to receive the results of the queries in chunks. At the moment, I am only rendering the top 200 results of the results and render more as one scrolls down. It would be great to have the queries behave in the similar way, so first just transfer the first 200 results and successively ask for 'the next 200' as one is scrolling down.

**Comment by ayya-vimala** [comment]
moved to issue #110
