### ISSUE TITLE
Loading of test files in Chinese, Pali and longer files

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#145]
Load test files for Chinese (T31 collection), Pali (MN collection) as well as some longer files in Tibetan and Chinese. 
@sebastian-nehrdich to select longer files in Tibetan and Chinese.

**Comment by TrebuhD** [comment]
The Chinese & Pali files have been added to the loading script. Waiting for @sebastian-nehrdich's list of longer files in order to close this task.

**Comment by ayya-vimala** [comment]
I think this issue is also about loading into the frontend and see how it behaves?
I tried loading the Chinese in the frontend but that seems to crash ... 
Pali does not work either. I'm getting an error:
`VM221:1 GET http://localhost:8000/files/dn11/segments?score=50&co_occ=2000&par_length=50 500 (Internal Server Error)`

**Comment by ayya-vimala** [comment]
For Chinese: T29_T1558.json
For Pali: ya7.2.3 but as the pali files are very split, I don't expect any problems there. 
For Tibetan:

**Comment by ayya-vimala** [comment]
Conclusion: apart from taking ages to load into the backend, T29_T1558 for instance took over 5 minutes to load in Numbers view and then crashed the browser.
Pali files are okay but those are much much smaller.
