### ISSUE TITLE
Create api endpoint for text-view test

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#193]
Create a simple api-endpoint that uploads the segments for use in the text-view.

**Comment by ayya-vimala** [comment]
This is set up on a separate branch (both on backend and frontend) so pull these two branches and work from there.

**Comment by sebastian-nehrdich** [comment]
Thank you for this, we have merged this on the frontend already, but the backend still needs some work (not yet merged). Once that is done we can close this I think.
