### ISSUE TITLE
Segment numbers not always matching

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#27]
#### Bug Description
I found another error/problem in the csv files that is messing up the highlighting of parallel segments in the text-view:
For instance in `pp1.3.csv` it says:

"1999302","LC`pp1.3:17.1`","   Atthekacco puggalo na sevitabbo na bhajitabbo na payirupāsitabbo, atthekacco puggalo sevitabbo bhajitabbo payirupāsitabbo, atthekacco puggalo sakkatvā garuṃ katvā sevitabbo bhajitabbo payirupāsitabbo. ","5.960#an3.26.txt#LC`an3.26:1.3`#373498#157459.0#   Atthi, bhikkhave, puggalo na sevitabbo na bhajitabbo na payirupāsitabbo."

So `an3.26:1.3` is mentioned there.
But when I go to the file `an3.26.csv`, number 1.3 is not to be found. Instead, the text 'Atthi, bhikkhave, puggalo na sevitabbo na bhajitabbo na payirupāsitabbo.' is mentioned as part of number 1.2 basically because the segments are taken together and the segments that are found as parallels do not match the actual segments in the source files.

"373493","LC`an3.26:1.2`","   Katame tayo? /   Atthi, bhikkhave, puggalo na sevitabbo na bhajitabbo na payirupāsitabbo."`pp1.3:17.1`,.....

This is the original source file from SuttaCentral:
  `"an3.26:1.2": "Katame tayo?",`
  `"an3.26:1.3": "Atthi, bhikkhave, puggalo na sevitabbo na bhajitabbo na payirupāsitabbo.",`

#### Expected behaviour
Each segment to have it's own number in some way. If that information is retained in the source file, the json conversion and frontend will be able to deal with that.

Update: For the Tibetan texts this already seems to be the case.

**Comment by sebastian-nehrdich** [comment]
I also suggest to close this, the code that generated the CSV files doesn't even exist anymore, so as you suggested, we probably run into new, different problems with the new Pāli files coming soon.
