### ISSUE TITLE
Generate Tibetan and Sanskrit Menu structure

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#30]
Currently we have no menu structure for Tibetan and Sanskrit in the frontend.
Sebastian will supply the data and Vimala will add it to the frontend menu.

**Comment by ayya-vimala** [comment]
Tibetan menu has been sent. But will still be adapted later.

**Comment by ayya-vimala** [comment]
@sebastian-nehrdich - just putting this here for you to send me the data once you have it.

**Comment by sebastian-nehrdich** [comment]
I have updated the Tibetan menu data (replaced the old ones). It has some adaptions mainly to save space (instead of TENGYUR01 its just T01 and I removed the file-endings).

**Comment by ayya-vimala** [comment]
There are still a few errors like for instance:

> K12	kl00553 'PHAGS PA SHES RAB KYI PHA ROL TU PHYIN PA'I MTSAN BRGYA RTZA BRGYAD PA (A'ARYA PRA DZNY'Am PA RA MI T'A N'A KA A'AshtA SHA TA KA NA)

Also, the files are not in number order so I have sorted that on my end.

**Comment by sebastian-nehrdich** [comment]
Yes you are right there are some bigger issues with the Kangyur files - I think it's better if we skip that for now because I will get a new list of the filenames very soon.

**Comment by sebastian-nehrdich** [comment]
Small note: Maybe better to have Kangyur on the left and Tengyur on the right side in the menu (reflects the division into Sūtra and Sāstra).

**Comment by ayya-vimala** [comment]
I also had a look at the Sanskrit files you sent. You say the menu structure matches up with the Tibetan. That is fine but the filenames and references do not. So for instance if abhisamu.csv matches up with T01T1234E (just as an example; I know that number does not exist), can it be called S01T1234E or something like that? Or I need a whole new menu structure that tells me which filenames should go where. Right now all I can do is make a dropdown box with all 337 items just listed by the filename and not in any structure.

**Comment by sebastian-nehrdich** [comment]
Yes You are right, I am sorry I didn't write this clearly: I wanted to say 'will match up', but I have to supply you with the new menulist. It will come soon! At the moment, nothing is matching. I wanted to say that the general structure of the menus will match, but not the individual files (so there will be the same categories in both cases).

**Comment by ayya-vimala** [comment]
Just wondering how late you work at night ... you seem to be working till the early hours now! Do get enough rest :-)

**Comment by sebastian-nehrdich** [comment]
I try to keep your advice in mind... There might be more time to rest once the presentation is over! :) :)

**Comment by sebastian-nehrdich** [comment]
I just uploaded the Sanskrit menu data and did some changes to the structure in the data-incoming folder:
* I removed the Tibetan categories file and created a joint categories file under data-incoming (we don't need to keep a separate file for each language I guess)
* sanskrit_files.csv in sanskrit/ holds the file-data for Sanskrit. I have now added the entire GRETIL with all the responding categories (they are listed in categories.tsv) because I am kind of optimistic that we can get this going for Paris. I might just gonna blacklist the files that have a strange formatting (even if we loose half of GRETIL then, it's not a big deal. GRETIL is a very selective canon anyway, and loosing some material will not be bad methodology. We should see it the other way round: Every text that we can add to the display is a valuable addition, we shouldn't be too worried about the fact that we might only be able to add a certain percentage of GRETIL at the current point). 
* I added a tag XX for all the Buddhist texts of GRETIL that are not yet integrated in the corresponding Tibetan category. This is not a beautiful solution but it works.

**Comment by ayya-vimala** [comment]
I think it should be easy to get it all going before Paris. Right now the sanskrit pages are rather old so need to be updated because I don't want to have to make each change to a view 3x (and still need to move common functions out to another js file). But it should not be too hard.
I just have a question on these categories. Do I take it correctly that f.i. `GK22	./5_poetry/5_subhas` means that it should be a structures that says:

> Poetry
> ---5 Subhas
> ---- Dropdown with:
> ------ksdarpiu
> ------vidsrgiu
> ------vidsrixu
> ------bharst_u
> ------vispancu
> ------vidsriau
> ------etc.

Do you also have a list with the actual names of these texts? It looks a bit strange I think to just have the filenames.

**Comment by sebastian-nehrdich** [comment]
Yes you got it right. Also in the case of Buddhist text, we probably (I just discussed it yesterday with Orna) want to divide it into three baskets: (1) Kangyur, (2) Tengyur, (3) misc (which means all the texts not yet classified). I think that division is already present in the menu file atm, but I didn't explain this before.
Regarding the Sanskrit file names, you are right, GRETIL filenames are close to unreadable. I have such a list and I will upload that today or tomorrow. We would also have a different naming scheme for the Tibetan categories including their Sanskrit equivalent - I will provide that also very soon.

**Comment by sebastian-nehrdich** [comment]
I just uploaded a new version of sanskrit_files.tsv which has the gretil-textnames added in a third column. it was not always possible to pull a name and the naming convention is also terrible so... this really needs some manuel work but I guess we will not be able to do much before Paris.

**Comment by ayya-vimala** [comment]
Thanks. I got it. Just a few questions:
There is one: amoghapu - which says TODO: K10. What does that mean?
And several others like nagcitau that have no collection assigned. Where should those go?

**Comment by sebastian-nehrdich** [comment]
Sorry for that, I fixed the file and uploaded the new version!

**Comment by ayya-vimala** [comment]
I've uploaded the menu so please have a look at that. It is indeed a bit of a mess but like you say, we have to find somebody to sort it out. I can ask on our forum is there is somebody who can do this. We have several scholars on there.

**Comment by sebastian-nehrdich** [comment]
It looks fine and you did a great job! However I have the slight feeling
that it might be better to use the Tibetan Sanskrit names instead of those
of GRETIL. I will check it and if their quality is better, I will upload
that list tomorrow (in the same format).

**Comment by sebastian-nehrdich** [comment]
The Sanskrit names from the Tengyur/Kangyur are not an improvement after all, so we might not follow that path! It's better to do that manually I assume.  
I have now updated categories.tsv and added English/Sanskrit translations of the category names. Sanskrit is unfortunately not always clear to me, this is why I couldn't add it in all cases. We might add the English to the menu entries, but it is not very urgent or necessary! Only if you have time for this.

**Comment by ayya-vimala** [comment]
Just to be clear:
On the Tibetan page we use the Tibetan names in the menu.
On the Sanskrit page we use the Sanskrit names of the Tibetan files.
Note that we do not have Sanskrit files for all Tibetan categories so I have only put in the menu those that we actually have files for. F.I. T08, T13 & T14 do not exist and for the Kangyur most of them don't exist in Sanskrti.

I'm afraid adding the English as well will create some problems with the space or very long menu names. Will have a look. Would you also want the English in the Tibetan AND Sanskrit menus?

**Comment by sebastian-nehrdich** [comment]
I discussed this with Orna: We should use the Sanskrit in both cases and
remove the Tibetan entirely. If it is space-wise possible, it would not be
bad to have the English in brackets behind the Sanskrit.
So one way to do this would be to replace  'DBU MA' with "Madhyamaka (The
Middle Way)".
If there is not enough space to do this, I will think about a scheme to
abbreviate things. just let me know how many characters per line max. are
acceptable for you, then I can work with that.

**Comment by ayya-vimala** [comment]
Okay, that's fine. Will do that today.

**Comment by ayya-vimala** [comment]
PS. Jātaka is not translated. I would translate that as "Birth Stories" ...

**Comment by sebastian-nehrdich** [comment]
Yes, sounds good to me... :)

**Comment by ayya-vimala** [comment]
For the dropdowns in the Tibetan text, we want to use the sanskrit names in conjuction with the TD numbers. 
Sebastian will generate a file that has all values in like:
T04 TD3910E	sakṛtprāveśikanirvikalpabhāvanārtha
I will then make sure it gets into the menu.

**Comment by ayya-vimala** [comment]
I've added a test title element to some of them:
Go to Tibetan - T06 the first two in the dropdown list. Hover over them and they show the title. Can probably also make something else like a tooltip.

**Comment by sebastian-nehrdich** [comment]
That's great! I will supply the full list with the Tibetan as well, that
would be very helpful.
Also would be nice if this works when hovering over the parallel segments
in the display of the quotes (both in table view and in text view). But it
is not urgent and nevermind, just a suggestion on my part!

**Comment by ayya-vimala** [comment]
Okay, I have made it into a bit more of a fancy css tooltip.
For the parallels that would be more difficult because the data is not readily there: it would require searching through another long json list to find that. Better to until wait after we have a database.

**Comment by sebastian-nehrdich** [comment]
I see!
For the time being, it looks good!
Two Sanskrit files have changed:
T07vakobhau.json was changed to T07vakobhau-1.json and T07vakobhau-2.json 
The same happened to T07yabhkvyu, which turned into T07yabhkvyu-1 and T07yabhkvyu-2.

**Comment by ayya-vimala** [comment]
I changed it in the menu.

**Comment by sebastian-nehrdich** [comment]
Thank you! I will aso change the file-category-lists  accordingly (also I
promised you a new list of Tibetan<>Sanskrit names for Tengyur and I am
also working on an updated list of Sanskrit filenames, this is all on my
schedule for the weekend).
