### ISSUE TITLE
SSL certificate & domain name

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#33]
Setup SSL certifcate and move to new domain name.
Setup new endpoints, leaving the old (working) site somewhere else and redirecting buddhist-db.de to buddhanexus.net.

**Comment by sebastian-nehrdich** [comment]
One note: The website is planed to be hosted at the university of Tokyo later, I will contact them about the http-settings (I suppose they use https, but I am not sure).

**Comment by TrebuhD** [comment]
The https certificate is linked to the domain, not necessarily the hosting provider. Do we have access to the domain provider for http://buddhist-db.de?

**Comment by sebastian-nehrdich** [comment]
Yes I have, I will look into this. Currently we are 'on our own' anyway regarding the hosting solution, so this should be straightforward. I will check it this evening.
