### ISSUE TITLE
Double entries in parallels in csv files

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#34]
#### Bug Description
The same text sometimes appears twice or more times in text. The system now picks that up as two separate parallels to a certain segment. However, this gives a distorted picture. It would be better that only the first entry was mentioned, maybe with a marker to show there are multiple entries in this specific file.

#### Expected behaviour
Only the first entry of that file to be mentioned for each segment of the source file.

**Comment by sebastian-nehrdich** [comment]
As we made some recent changes to the JSON files (introducing the offset values), it would make sense to rethink how we can approach the case of longer segments where two different quotes appear in the same segment. This is not so much an issue for the Sanskrit and Tibetan data that we worked with up to now, but it would make sense to think about how we can solve this issue. I have no idea currently on what would be a good way to deal with these cases, but we should keep in mind that we will run into this problem at some point!

**Comment by sebastian-nehrdich** [comment]
This is all heavily outdated. I think we can close all issues that refer to the earlier generation of CSV based output.

**Comment by ayya-vimala** [comment]
This was for the pali files first output so as not to forget that this error happened. But we might run into completely different issues now so okay to close I guess.
