### ISSUE TITLE
Illogical output entries in csv files

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#35]
#### Bug Description
Parallel entries don't seem to have anything to do with the source segments in the CSV files.

#### Expected behaviour
As per the screenshot, there are entries with probability 0 that do not match the source segment at all while others with a high probability are an exact match.

#### Screenshots
![unnamed.png](https://images.zenhubusercontent.com/5cdda43f145f41296ed527b4/9b137ae7-7110-428b-acd4-1678d5cb6c21)

**Comment by sebastian-nehrdich** [comment]
I suggest to close this as well...
