### ISSUE TITLE
Creation of bilingual JSON files

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#37]
Creation of bilingual csv files for Tibetan / Sanskrit. After which this can be displayed in the Tibetan View per parallel.

**Comment by sebastian-nehrdich** [comment]
Hopefully I can upload the first examples on Saturday.

**Comment by sebastian-nehrdich** [comment]
I have now uploaded an example json under data-incoming/skt2tib. 
If there is anything you want to change about the layout of the JSON, please let me know!

**Comment by ayya-vimala** [comment]
First of all I noticed that the Sanskrit is still in it's tokanized form: `VasubanDu TriMSikA vijQapti kArikA` so that has to change.
I have answered you in the other issue. 
My apologies for giving you so much extra work!!! I think your initial idea is probably right: at some point we will also get links with pali in it and other Sanskrit /Tibetan text links and it will become much too confusing ...

**Comment by sebastian-nehrdich** [comment]
I will fix that with the tokenization. But generally - do you prefer to have this data together with the other quotes (so having the SKT-parallels along the tbetan parallels in one file) or do you prefer to have them split like it is right now? The later one might mean more work on the frontend level, but the data layout is a bit cleaner in my oppinion.

**Comment by sebastian-nehrdich** [comment]
Bilingual data should now be added to some of the JSONS. Please see under data-incoming/bilingual for the lists of files that are bilingual t the moment.

**Comment by ayya-vimala** [comment]
I noticed that TD4064E is o longer in the list but the files still lists the tests:

>     {
>         "segmentnr": 1,
>         "segment": " rgya gar skad du /",
>         "parallels": [
>             {
>                 "probability": 100,
>                 "parsegnr": [
>                     "test:1",
>                     "test:2"
>                 ],
>                 "parsegment": [
>                     "rgya gar skad du /",
>                     "trim shi ka bh'a shyam /"
>                 ]
>             }
>         ]
>     },

Then for other bilingual files: I think the bilingual parts needs to be probability 100% and not 0.

I have not looked further yet because I have to go now. Will have a better look later.

**Comment by sebastian-nehrdich** [comment]
Yes regarding the probability, I am fixing that!
And let's for the time not worry about missing files. I have created a big batch process for the creation of the bilingual files and it is outputting about 10 files/hour. It is still running and might take another night to complete. I am uploading the files every now and then so the number of bilingual files is steadily increasing. TD4064's will be later tonight I guess... :)

**Comment by ayya-vimala** [comment]
Some other things I came across in testing one: T06bsa010_u.json
The first segment is empty. Not a big deal I guess but looks a bit strange.
```
    {
        "segmentnr": "",
        "segment": "",
        "parallels": []
    },
```
Then the next segment has a parallel that just consists of dandas:
```
    {
        "segmentnr": "P:0_0",
        "segment": " Āryamaitreyapraṇītā Madhyāntavibhāgakārikā (Mvk) /",
        "parallels": [
            {
                "parsegment": [
                    "//"
                ],
                "parsegnr": [
                    "TD4021E:0"
                ],
                "probability": 100
            }
        ]
    },
```
And also consistently throughout is that the Tibetan parsegnr do not have the directory in it. It says "TD4021E:0" instead of "T06TD4021E:0" so it cannot find that one in the text view and does not classify it in number view.

If I find any more I will post it here.

**Comment by sebastian-nehrdich** [comment]
I would like to change a bit how we do this (but after Paris!): 
- Currently, I am inserting the multilingual parallels into the monolingual json-files and this kind of works. However it's not  a very clean solution and creates a lot of problems during time of data generation. 
- I would rather have a seperate folder under suttas/ which is called 'multilingual' and have the multilingual parallel hosted there.
- for example: in the case of T06TD4064E.json, we will not add any Sanskrit to the file under sutta/tibetan/T06/ but instead create a copy which is stored under multilingual/ with the same name. When we load T06TD4064E.json on the frontend, we *also* check the folder multilingual/ if a file with that name exists there. If it does, we open that as well. 
- The file in the folder multilingual/ will be just a big json dictionary. Each segment of the Tibetan file will be used as a key, and the value will be the multilingual parallels for that key. 
- We do the same for the Sanskrit texts and their Tibetan parallels, so for example for T06bsa10.json, we create a copy that is stored under multilingual/ and which does contains a big dictionary with each of the segment of T06bsa10.json as key and the possible multilingual parallels as values. 
- on the frontend, we need to load these dictionaries if they are avalaible and then check for each segment that we are iterating through in the display if a parallel is present in the multilingual file. If yes, insert it to the display. 

I know this adds a bit of complexity to the frontend but I really don't like to mix this data as it is right now. it is extremely difficult to trace at the moment which texts has parallels and which not and also I have to regenerate the entire dataset (more than 6GB per language) and reupload it after each bilingual text I added. That really is not a very sound solution I think.

**Comment by ayya-vimala** [comment]
I wouldn't do that. I think we should concentrate on a database and then that will be completely different and whatever json files you produce then will not be read by the frontend but by the database using python and the frontend just sends queries to the database. So then the frontend will be completely changed due to that.
