### ISSUE TITLE
Move all the text data to buddhist-db and link by absolute path?

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#42]
I am not sure about github's policy regarding bandwidth/webspace, but since we are now in the stage of adding more and more texts, we might just move them directly on buddhist-db.de and link to the absolute paths in the webapp? The small Tibetan and Sanskrit collections we are working on right now already take up a few hundred megabytes each, once we go for a full-blown upload we will have a coupe of GB at least. I think it might be better to have just the code and some small datasets (like the menu files etc.) on github and the rest externally.

**Comment by ayya-vimala** [comment]
I think this can be closed.
