### ISSUE TITLE
Table view: Sort by different criteria

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#45]
Suggestion by Orna: Currently in table view, we are sorting by the order of the text (so quotations are presented in accordance to their occourence in the root text on the left side). It would be nice to sort the quotations also by other criteria, for example by the text that they are taken from or by their length.
(this is not urgent)

**Comment by sebastian-nehrdich** [comment]
@ayya-vimala Orna reminded me these days again that this would be nice to have. I suggest to have a drop-down menu in table view with three options: Sort by position in text (default, this is what we have at the moment), Sort by length, Sort by name of the quoted text.

**Comment by ayya-vimala** [comment]
This will take me a while to do. We really have to have a meeting to see what is most important. The highlighting took me about 40 hours. When people don't know about the programming they always think that's it's a quick and easy thing but then in practice it is not so easy and takes a long time and time is limited.

**Comment by ayya-vimala** [comment]
Hold on ... reading it again I'm confused. You can do all those filters already in the tables.

**Comment by sebastian-nehrdich** [comment]
Yes I appreciate your hard work on the highlighting and I can totally
understand what a big mess this can become!
I also agree that most of the things can already be accomplished by
filters. Orna wants to sort the results, but mhmm, if I am honest I also
believe that this could be a bit more tricky on the technical side. One has
to collect all quotes, seperate them from the data, then construct a new
array, sort that and so on. It's not really straight forward. I will
discuss it again with her.
In my eyes not really necessary, I get your point! Possibly it's better to
improve just the filters and add a few options and that should be enough.

**Comment by ayya-vimala** [comment]
I see what you mean. This might also be much easier with a database. One more reason to convince her :-)
I have a bit of a feeling that we are already stretching what can be done without a good database and I'm surprised what has been acomplished without one (mostly thanks to your ideas).

**Comment by sebastian-nehrdich** [comment]
Yes me too! I think we might just refuse the sorting option without a
database. Once we have queries we might have to reimplement it anyway and
it doesn't seem to be very essential at the moment! So let's stash it and
focus on the other things.

**Comment by sebastian-nehrdich** [comment]
One quick thing: in the description of the length filter, please change max
length to min length because that's how the filter works! I just noticed
this.

**Comment by sebastian-nehrdich** [comment]
@ayya-vimala the new offset highlighting broke the segment view mode, so we need to give that an overhaul. We should take this opportunity to make some deeper changes to the segment view in my eyes. 
What we need urgently is an option to sort the matches [request by O]. So I think the strategy of the segment display should change a bit. I am thinking of the following:
- currently, we 'double' each parallel for every rootsegment in which it occours. Not ideal - we should rather iterate over all quotes in advance, remove duplicates and collect the entire rootsegment for the relevant quote. Then we construct a new array and use that as a base for building the table view. I know that with a DB this will also be cleaner but it can be done already right now and I get the feeling that if this feature is not going to come very soon, people will get more unhappy. In this way we don't have any double items in the table anymore and we get rid of the problem that currently, quotes are displayed stretched over various root segments 
- after doing that, I think sorting should become a rather managable affair. One naive way to do this would be to just sort the new array by special keys (root segment, length, target-text and co-occurence come to my mind) and then update the display. If performance is going to be very bad we might think about using some lit-html-strategies to update the DOM without re-rendering it but maybe that's not necessary

**Comment by sebastian-nehrdich** [comment]
I implemented this now roughly. I noticed there are some smaller bugs left, also the highlighting in segment view on the left side is yet missing. But it does what it should do now. 
It would be great to have a dropdown-element in the frontend to let the user choose between different kinds of sorting methods. I wrote some comments in the code so hopefully you can understand what I mean!
It's all in the new-offset-highlighting-branch.

**Comment by sebastian-nehrdich** [comment]
I have now added a dropdown for segment-view so different sorting options become available.
