### ISSUE TITLE
Changes to the text view mode 

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#46]
Some smaller changes suggested by Orna that we might be able to integrate for Paris (ordered by priority; if we cannot integrate these, that is no problem):
- the highlighting of the matches on the left side (root segments) is not very noticable at the moment. I think she means the fact that the distinction between normal text and the grey text on some displays (like her computer) is barely noticable. She suggests us to use a different color, for example blue.
- it would be nice if in the text display on the right side (the most right column showing the quoted text), we could also highlight those parts of the of the texts that are quoted as well, but not currently selected. This would be very nice in order to be able to compare one text against another

**Comment by ayya-vimala** [comment]
probability filter change to moving bar.

**Comment by ayya-vimala** [comment]
I've moved the second part of this issue to issue #49 .
I also created issue #50 for the sliding bar for the probability filter.
First part of this issue is done (at least in blue). Let me know if this is sufficient.

**Comment by sebastian-nehrdich** [comment]
I mentioned this already in another comment, but currently it seems to me that those things which don't have a parallel are marked blue, but shouldn't it ideally be the other way round? 
Another thing I noticed: In text-view, after clicking on a quote in the left column for the first time, the size of the left column changes when the quotes in the middle column appear. I find this to be just slightly annoying. Also, when I click for the first time on a middle quote, once the text on the right side has finished loading the size on the leftmost column changes once again (usually becomes very small at this point). However this all happens only on the first time; if I choose a different quote etc. later, the sizes don't change. I would prefer if we just split 1/3 1/3 1/3 for each column and keep it that way (until the user of course decides to change the column sizes manually), or is there a reason why it is like this at the moment?

**Comment by ayya-vimala** [comment]
I thought if we would make text with a parallel in blue it would be a whole lot of blue so this seemed more natural. But if you want I can change it around.

The issue with the columns I noticed too and I tried dealing with that but that did not work. I think I will have to ask Vaadin how to do that.

**Comment by sebastian-nehrdich** [comment]
Yes I see what you mean. I suppose that's because in previous versions of the software, they just could compare max. two texts at once and thus the amount of parallels was much lower and such a way of highlighting made sense. In our current data-collection the user needs to apply filtering in order to have anything useful of the highlighting. Anyway I will ask Orna and see what she thinks about this.

**Comment by ayya-vimala** [comment]
Have a look at T06TD4023E - there is masses of blue there. That is what it would look like if it was the other way around.
I had a look at the splitter and made a few changes. I cannot prevent it from calculating a new width each time UNLESS the user changes the width once manually ... then it stays the way the user selected it. The only thing I can do is to give it a minimum width so then it will never become smaller than that but that also means you cannot make it smaller if you want to. (not yet uploaded this ... will do tonight).

**Comment by sebastian-nehrdich** [comment]
Please don't worry too much about the splitter, it is not such a big issue.
A minimum width for the left column however would not be a bad fix for the
time being!

**Comment by ayya-vimala** [comment]
I've set a minimum to a quarter of the view port now. That will not look too bad.

**Comment by ayya-vimala** [comment]
Please also ask Orna about the text colors of the first column. I can change them around so blue = parallels and black = no parallels.

**Comment by sebastian-nehrdich** [comment]
Will do that!
