### ISSUE TITLE
Highlighting all quoted parts of the relevant sutta and not just the selected segment

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#49]
it would be nice if in the text display on the right side (the most right column showing the quoted text), we could also highlight those parts of the of the texts that are quoted as well, but not currently selected. This would be very nice in order to be able to compare one text against another.

**Comment by sebastian-nehrdich** [comment]
Suggestion by Orna: Having the color of the parallel passages in the right window in red.

**Comment by ayya-vimala** [comment]
I think this can be closed now.
