### ISSUE TITLE
Change probability filter to sliding bar

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#50]
Instead of typing in a number, use a sliding bar to display probabilities.

**Comment by sebastian-nehrdich** [comment]
I think I can do something on the data level to make your life easier. 
As we discussed yesterday, the similarity values are very sensitive and can be completely different for each language. So for Tibetan, we might end up with reasonable values between 0.0 and 0.04, for Sanskrit they could be between 0.0 and 0.07 which is a huge difference. 
So I think I will take this into account when I generate the JSON files and I will replace the similarity value with a number between 0 and 100 with 0 meaning no similarity and 100 meaning identical. This will be the same across all languages, so you don't have to worry about this on the frontend level.

**Comment by ayya-vimala** [comment]
I would not worry about this.This won't be for Paris because there is another issue with sliders, namely that you need to have a submit button in addition to them otherwise it starts to reload data while you are not yet done sliding. I want to rethink if this is really a good idea for several reasons and just made the issue so as not to forget. There are a few webcomponents by Polymer that can be used for that.

**Comment by ayya-vimala** [comment]
Agreed was that Sebastian will change the scores to a scale of 1 to 100 and then the sliding scale is easy to do with 
https://www.webcomponents.org/element/@polymer/paper-slider

**Comment by sebastian-nehrdich** [comment]
The interface looks already nice, i will update the files now accordingly. 
Small suggestion: Could we add a tooltip that says something like 'set 0 for lowest and 100 for highest similarity'?

**Comment by ayya-vimala** [comment]
Okay .. done.

**Comment by sebastian-nehrdich** [comment]
looks all great, from my side this can be closed.
