### ISSUE TITLE
Small things about the interface

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#54]
There are two more things I noticed regarding the interface that would be nice to change for Paris:
1. Could we make text-view the default mode and have table-view and number-view as second and third alternative? Orna and me thought that text-view might be good for starting to read the files
2. The number-view with the scrollable table looks awesome. Would it be possible to expand the category title at the top with the Sanskrit/English? In this way, it becomes easier for the user to understand which category has which meaning. Of course the table might become very wide because of that - maybe we can try to use line-breaks in the names or work with tooltips... :)

Anyway, our page really looks great! Can't wait to add the bilingual data and the visualizations tomorrow.

**Comment by ayya-vimala** [comment]
I have added tooltips to the categories in the number view.

**Comment by ayya-vimala** [comment]
Also changed the text view to the first place and made it default.

**Comment by sebastian-nehrdich** [comment]
Great, works! 
An obversation I made today: Sometimes, after watching one texts, when one opens a new file from the dropdown menu, the text is not updating properly in the text-view and the old text is still shown. This changes when one clicks on a segment to see the parallels... Seems to be some problem with the refreshing of the JS here I assume.

**Comment by ayya-vimala** [comment]
Hmm ... can you get me some steps to reproduce this error?

**Comment by sebastian-nehrdich** [comment]
I will do so tomorrow! Maybe it has something to do with my Webbrowser...

**Comment by ayya-vimala** [comment]
That reminds me: testing on FF needs to be done. FF might be behind in the technology on webcomponents. And forget about Edge ... won't work at all!

**Comment by sebastian-nehrdich** [comment]
And one more small thing: could we change the default similarity cutoff to
zero percent? I think that makes a bit more sense...

**Comment by ayya-vimala** [comment]
Okay ... done. 
FF works fine too.
