### ISSUE TITLE
Table views: Add option to disable segments without parallels

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#56]
I was thinking: It would be helpful if we add an option in the table-view to not show segments that do not have a parallel. For example yesterday I wanted to check which sections of the Abhidharma-kośa-bhāṣya quote the mahābhārata and there are quite some, but there are many hundred segments without a parallel in between them, so it becomes a bit tiresome to scroll through all the texts. having a small checkbox with the option "don't show segments without a parallel" would be helpful in my eyes!

**Comment by ayya-vimala** [comment]
Maybe, or just not show them to start with. There does not seem to be any value in having empty boxes.

**Comment by sebastian-nehrdich** [comment]
I agree!

**Comment by ayya-vimala** [comment]
I've done that for the numbers-view (not yet uploaded). How about the segment-view?

**Comment by sebastian-nehrdich** [comment]
Thank you. For segment view, I think it should at least be an option (maybe
not a default though)!

**Comment by ayya-vimala** [comment]
All done too.

**Comment by sebastian-nehrdich** [comment]
Great, works!
