### ISSUE TITLE
Find somebody to setup database Mongo/Arango

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#61]
**Background:**
Setting up a database will increase speed and make the whole dataflow more fluid and easy to manage.
Right now json files can be gigantic.

**To do**
Try to get a good developer who is able to do this.

**Preferable Profile:**
* Experience with database setup and python
* Experience with javascript and preferably with polymer/lit-element webcomponents
* If at all possible some familiairity with ancient (Buddhist) Texts but not absolutely necessary
* Able to work as freelancer for some time. There might be possibilities for a fixed contract later but this is uncertain.
* This can be a part-time job

Vimala will draft an email and ask H for feedback/quote.

**Comment by sebastian-nehrdich** [comment]
I have also posted a similar search on some German computer science student networks, just in case we need to look out for someone else.

**Comment by sebastian-nehrdich** [comment]
I think we found somebody, should move this to review/close it or do you want to keep it open until the contract is signed?

**Comment by ayya-vimala** [comment]
I thought I had closed this issue ... anyway, what is the status of the contract so I can let Huber know?
