### ISSUE TITLE
Sankey webcomponent

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#64]
Right now the Sankey is not inside the lit-element. This has to be changed over to webcomponent inside visual view.

**Comment by ayya-vimala** [comment]
I finished this but only opening items on the left side. Also, it is a bit difficult (as you will have noticed) to find an appropriate height for some of them.
I chanted the folders k_t and t_k because they seemed to have the opposite data in them. It seems logical that k_t refers to Kangyur to Tengyur but it seemed to have the Tengyur to Kangyur items in it. 
Will have everything uploaded to the server in a few hours.

**Comment by sebastian-nehrdich** [comment]
regarding the folder-names of k_t and t_k, I did it that way in the first
place but I remember that there was something twisted about this and I ran
into a big problem then and I fixed it by manually renaming the folders.
But maybe my intuition was wrong at that time, I don't remember it so
clearly anymore, will have a look at it again when you have uploaded it to
the server!

**Comment by ayya-vimala** [comment]
Finally uploaded (I think, there were a few crashes).
Sometimes just the calculations of the height are not that great ... not sure what to do about it. You had a factor 10 which I changed to 4 because it seemed to fit better for most collection combinations, but obviously not for all ... so not sure what to do about that.

**Comment by sebastian-nehrdich** [comment]
I put 10 because it avoids the crashing with the large collections (had 4
first but that breaks things). One could change this factor according to
the size of collections, e.g. set 10 when the collection is larger than X
and a smaller value when we can allow that and it doesn't break things
anymore...

**Comment by ayya-vimala** [comment]
Yes, you are probably right. I thought of that too but was hoping you had another solution. Fine, will change that.

**Comment by sebastian-nehrdich** [comment]
No nothing better on my mind. I have the feeling that the
webcomponent-version of this library is not as well debugged as the
d3s-version, so we have to accept some oddities but all in all it is usable
I think.
I noticed (and this also explains to me why you flipped the folders k_t and
t_k) that in your version now left and right side are flipped. No big deal
to me, we can keep it that way imho.
