### ISSUE TITLE
JSON generation Chinese

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#73]
I will have to submit my draft for the paper on Chinese soon (15.8.) and it therefore is getting a bit more necessary for me to look at the Chinese material now. 
The aim is do include Chinese material for the first launch of the website. The technical situation here seems to be a bit less complex than with Sanskrit, Pāli or Tibetan. 
The Chinese Taisho (let's call it T from now on) is already structured in a somewhat similar way as the Tibetan canon, so doing the visualization etc. might be straightforward. The number of text is also not too frightening, I am counting 4000 (comparable to the Tibetan). I am a bit afraid that we will have the same problem with the visualization that we already have for the Tibetan canon, that is to say too many texts and not enough space on the screen to display them all. 
I will try to generate the JSONS in a way that they wil be maximum compatible to the Sanskrit/Tibetan versions. Probably I will have to ask you to help with the generation of the menus for the Chinese once the data is available.

**Comment by sebastian-nehrdich** [comment]
A small set of Chinese JSON files is now on the server under suttas/chn for testing purpose. I also added a menu in the menu-test branch. As I mentioned in the isue on the menus, the only thing missing now is the link between the menu and the files so that the loading after clicking works. I am slowly running out of time for today, might have to wait until tomorrow before I can continue to work on this! If you could have a look? Of course only if you have time, no rush with this.

**Comment by ayya-vimala** [comment]
I had a look at the files and noticed why they are not loading: the filenames do not match the segment numbers. The file name is for instance 'T30_T1564:3_0' while the segment number is 'T30#T1564:3_0'. Can we somehow keep it the same? Maybe best the same system as the Tibetan with `T30T1564:3.0`? The more consistent the jsons are with each other the better it is.
Other than that everything looks just fine.

**Comment by ayya-vimala** [comment]
Another thing I found is a begin and end-offset of -1. I think beginoffsets should never be -1:
```
        "segmentnr": "T30_T1564:41_1",
        "segment": "姚秦三藏鳩摩羅什譯",
        "lang": "chn",
        "parallels": [
            {
                "probability": 100,
                "parlength": 10,
                "parlang": "chn",
                "par_offset_beg": -1,
                "par_offset_end": -1,
                "parsegnr": [
                    "T32_T1646:5_1",
                    "T32_T1646:6_1"
                ],
```

**Comment by ayya-vimala** [comment]
And another weird one:
```
            {
                "probability": 100,
                "parlength": 6,
                "parlang": "chn",
                "par_offset_beg": 2,
                "par_offset_end": -1,
                "parsegnr": [],
                "parsegment": [],
                "root_offset_beg": 5,
                "root_offset_end": 12,
                "root_segnr": [
                    "T34_T1718:9_1"
                ]
            },
```

**Comment by sebastian-nehrdich** [comment]
I have updated all the JSON data on the server yesterday. If you still find anything odd, please let me know! 
I have noted during data generation that among the billions of quotes (literally, hundreds if billions!) there are maybe a few dozen of quotes where the parsegnr and/or root_segnr values are still empty. I suppose this must be some very weird cases of faulty input data and it is close to impossible for me debug. I hope we don't run into serious problems because of these. 
I am now waiting for M's feedback and then I will start to generate the full dataset (T+X). It's truely a task and even though I have a lot of memory at hand it is actually not enough to hold the entire dataset. For Chinese, I have to create two nmslib-indicies and then run this in four batches (X against, T, X against X, T against T, T against X)  to get this done. Each batch might take something like six to eight hours to finish. With nmslib I have the feeling that calculation time raises exponentially with dataset size. So 200mb of Sanskrit are done in one hour but 600mb of Chinese will take their 24 hours at least...

**Comment by ayya-vimala** [comment]
I bet it is a huge job. Are there still any empty ones do you think? I can build something in JS to make sure that at least it does not crash in that case.

**Comment by sebastian-nehrdich** [comment]
Never mind. I think we have maybe two or three of such cases among the
billion of quotations in the collection... As long as the file itself can
load it is fine I think. Or does the entire file crash if such a case is
present?

**Comment by ayya-vimala** [comment]
It only means that it cannot load the number-view. And when in text-view you click on the segment in the left side, it does not open the parallels for that one but it works for all the other segments.

**Comment by sebastian-nehrdich** [comment]
I think that's fine. I will also add validator to my script to filter such
cases.

**Comment by ayya-vimala** [comment]
So I guess this issue can be closed then. If more bugs show up we can make a new issue for those.
