### ISSUE TITLE
Chinese text loading has errors

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#77]
#### Bug Description
Various things to the Chinese text loading do not work.
1. Right panel does not load in text view mode.
2. Segment and numbers view don't work.
3. Where do linebreaks need to go?
4. Add collection values for collection filter.
5. Add Chinese font.

**Comment by ayya-vimala** [comment]
@sebastian-nehrdich - Can you answer question 3? 
Also, if you notice other things that don't work in the Chinese, please let me know.

**Comment by sebastian-nehrdich** [comment]
line breaks at the moment at the end of each segment. Paragraph break at
the end of a segment where segment-nr ends in _0!

**Comment by ayya-vimala** [comment]
Should the paragraph break not before the segment that ends in _0 instead of after?

**Comment by ayya-vimala** [comment]
Things should work as soon as I have:
1. jsons with errors removed and same segmentnr as filenames (see separate issue).
2. collection data for Chinese similar to Tibetan:
```
export const tengyurCollection = {"T01": "(Praises)",
                              "T02": "Tantra (Tantra)",
                              "T03": "Prajñāpāramitā (Perfection of Wisdom)",
                              "T04": "Madhyamaka (The Middle Way)",
                              "T05": "Sūtra (Commentaries)",
                              "T06": "Vijñaptimātra (Mind Only)",
                              "T07": "Abhidharma (Abhidharma)",
                              "T08": "Vinaya (Monastic Discipline)",
                              "T09": "Jātaka (Birth Stories)",
                              "T10": "Lekha (Epistles)",
                              "T11": "(Logic)",
                              "T12": "(Language)",
                              "T13": "(Medicine)",
                              "T14": "(Arts and Crafts)",
                              "T15": "Nītiśāstram (Mundane Treatises)",
                              "T16": "(Various)"};
export const kangyurCollection = {"K01": "Vinaya (Monastic Discipline)",
                              "K02": "Śatasāhasrikāprajñāpāramitā (Perfection of Wisdom in 100.000 lines)",
                              "K03": "Pañcaviṃśatisāhasrikāprajñāpāramitā (Perfection of Wisdom in 25.000 lines)",
                              "K04": "Aṣṭasāhasrikāprajñāpāramitā (Perfection of Wisdom in 8.000 lines)",
                              "K05": "Aṣṭadaśasāhasrikāprajñāpāramitā (Perfection of Wisdom in 18.000 lines)",
                              "K06": "Daśasāhasrikāprajñāpāramitā (Perfection of Wisdom in 10.000 lines)",
                              "K07": "(Various Teachings on the Perfection of Wisdom)",
                              "K08": "Ratnakūṭa (Pile of Jewels)",
                              "K09": "Avataṃsaka (The Majority)",
                              "K10": "Sūtra (Collection of Sutras)",
                              "K11": "Nirvana (Nirvana)",
                              "K12": "Tantra (Secret Teachings)",
                              "K13": "(Native Catalog to the Kangyur)"};

export const totalTibetanCollection = Object.assign({}, kangyurCollection, tengyurCollection);
```

**Comment by sebastian-nehrdich** [comment]
as I said in the other comment, I am very happy about how you handled the paragraph breaks at the moment. There are a few things that remain on my mind atm: 
- you seem not to do line-breaks after segments that end in _1 at the moment. I wonder if it is possible to have an 'optional linebreak' which is only applied when the window is wide enough, but will be disregarded when the window is too small. This is what I would like to have after segments that are ending in _1. If something like that is not possible (I really have no clue), then we should just not do any linebreak at all. 
- Regarding the mismatch between file-names and segmentnames: I used '#' characters in the files initially to seperate category and filename. But this is not good because the '#'-character shall never be used in URLs. I then had to change it all back to underscores but I forget to fix the content of the JSON files. i will fix that very soon.

**Comment by ayya-vimala** [comment]
You cannot see the changes I made because I first need the changes to the json files to show them. So there is no point commenting on this yet.

**Comment by sebastian-nehrdich** [comment]
I just updated the JSONS in chn/ on the server, please have a look. Some errors are fixed, but probably not all!

**Comment by ayya-vimala** [comment]
Great thanks! Will have a look now.

**Comment by sebastian-nehrdich** [comment]
oh no, I can tell you in advance that the offset-values if quote a lot of quotes seem to be just zero. I will have a look into this later today! Taking a break now.

**Comment by ayya-vimala** [comment]
I bet you must be exhausted after all this work! Okay, I will wait with testing.

**Comment by sebastian-nehrdich** [comment]
OK I could fix some of it and uploaded the new files, maybe you want to
have a look at the now. Parallel file loading seems to be generally working
now. If you could point me out what is still wrong with the JSONS that
would be great. Seems to me that the offset-values seem a bit strange
sometimes still.

**Comment by ayya-vimala** [comment]
I just took a random one but as long as there are things like this in it it keeps on crashing:
```
            {
                "probability": 100,
                "parlength": 7,
                "parlang": "chn",
                "par_offset_beg": 5,
                "par_offset_end": -1,
                "parsegnr": [],
                "parsegment": [],
                "root_offset_beg": 16,
                "root_offset_end": 8,
                "root_segnr": [
                    "T31_T1590:8_0",
                    "T31_T1590:9_1"
                ]
            },
```
Of course I can make an exception for such things in the frontend but it is not right.
I just took some random files:
T31_T1590 has 29 of such occurences and T31_T1586 had 28.

**Comment by sebastian-nehrdich** [comment]
Thank you for pointing that out. I could fix the error and am uploading the new files now.
The new files look generally good. I have the impression that root_offset_end is wrong at times, will debug that today. 
One thing to notice: I have now enabled static compression on nginx and zipped all json-files in gzip-format because I am totally running out of disc space on our small test server. So if you want to access the contents of a json you need to do gzip -d before in order to uncompress it.

**Comment by ayya-vimala** [comment]
Maybe the uni could invest in more space? Just a suggestion ... we also need the Sanskrit and Pali files at some point and the database will take a bit of space too.

**Comment by ayya-vimala** [comment]
I'm testing a few things. In T30_T1564 I found another one of those which crashes stuff. One thing I can do is to make an exception in the frontend so it just jumps over such things and then print something in the console to tell you that this is happening. Otherwise it becomes difficult because filters and table do not work properly.
```
            {
                "probability": 46,
                "parlength": 6,
                "parlang": "chn",
                "par_offset_beg": 0,
                "par_offset_end": -1,
                "parsegnr": [],
                "parsegment": [],
                "root_offset_beg": 0,
                "root_offset_end": 5,
                "root_segnr": [
                    "T30_T1564:855_1"
                ]
            },
```

**Comment by ayya-vimala** [comment]
On a separate note I noticed that you have parallels no longer limited to 10 so files have become longer because of that. Is that deliberate?

**Comment by ayya-vimala** [comment]
I also noticed a bug in the offset numbers but that is probably what you meant. I was wondering why the offset was not calculating correctly on for instance this:
```
            {
                "probability": 2,
                "parlength": 6,
                "parlang": "chn",
                "par_offset_beg": 10,
                "par_offset_end": 19,
                "parsegnr": [
                    "T48_T2016:15253_1"
                ],
                "parsegment": [
                    "依所執及隨有為。以辯唯識。三十頌云。由假"
                ],
                "root_offset_beg": 0,
                "root_offset_end": -1,
                "root_segnr": [
                    "T31_T1586:3_0"
                ]
            },
```
But that is because the end-offset is the same as the length of the segment so it should be -1.

**Comment by ayya-vimala** [comment]
And the following is also problematic:
```
                "probability": 42,
                "parlength": 6,
                "parlang": "chn",
                "par_offset_beg": 21,
                "par_offset_end": 28,
                "parsegnr": [
                    "T54_T2128:57912_0"
                ],
                "parsegment": [
                    "躁[打-丁",
                    "夒]上子到反下饒沼反前集異門足論第十卷中已釋訖。"
                ],
```
There is one parsegnr and 2 parsegments and two very weird offsets that don't seem to work with the segments.

**Comment by sebastian-nehrdich** [comment]
Thank you very much for pointing out these remaining problems and giving
concrete examples, so I have a place to start the debugging.

**Comment by sebastian-nehrdich** [comment]
And regarding the limitation: Yes that is deliberately because I asked M for feedback on the quality of the results (in order to make reasonable choices regarding the cutoff values), this is why we need to get as many parallels as possible. Of course it is also a kind of 'training' to what amount of data we might expect when we have a database. This is now looking more like the real thing...

**Comment by sebastian-nehrdich** [comment]
I have been debugging this stuff for the entire day today. I could pull out at least three major bugs and I will upload the updated files soon (I am waiting for calculation to finish and hope I can replace the files in about 2-3 hours). 
I noticed that currently, your code that calculates the blue highlighting on the left does not seem to count multiple whitespaces, while my offset-value do include multiple whitespace in the case of Chinese. This is why sometimes the blue highlighting does not work properly, even though the JSON files are somewhat ok. I can imagine that this might also be a big nasty to fix, so don't feel stressed about it! Just wanted to mention it, it's not a problem that occurs very frequently.

**Comment by ayya-vimala** [comment]
That is weird ... I will have to have a look at that later. I cannot see anything in the code that would do that. Maybe it's an html object thing but the quick look I had seemed to be okay. Can you give a concrete example of which file and which segment?

**Comment by sebastian-nehrdich** [comment]
Yes! 
I uploaded the following file to the server: T31_T1599.json
You can distinguish it from the old version because it is not gzip. 
In the JSON I have the following: 
```
{
        "segmentnr": "T31_T1599:10_1",
        "segment": "為我等宣說   今當顯此義",
        "lang": "chn",
        "parallels": [
            {
                "probability": 30,
                "parlength": 6,
                "parlang": "chn",
                "quote_unsandhied": "為 我 宣 說 我 等",
                "quote_unsandhied_end": "",
                "quote_position_beg": 51509073,
                "quote_position_last": 51509073,
                "par_offset_beg": 10,
                "par_offset_end": 17,
                "parsegnr": [
                    "T23_T1442:2750_1"
                ],
                "parsegment": [
                    "[口*兄]。唯願世尊為我宣說。我等聞已咸共受持。"
                ],
                "root_offset_beg": 3,
                "root_offset_end": 13,
                "root_segnr": [
                    "T31_T1599:10_1"
                ]
            },
```

But only the first character 爲 is highlighted as far as I can see! root-offset is going from 3 to 13. I could imagine that the error might be happening if the root_offset_end is exceeding the length of the current root segment. In that case, I would just suggest to mark until the end of the segment and leave it to that...

**Comment by ayya-vimala** [comment]
Yes, this is happening because root_offset_end is 13 and the length of the segment is only 13 including whitespaces. So it should be -13 and then the calculations do not know what to do so they don't do anything. If it would be 10 for instance, it should be okay. It has nothing to do with the white spaces in the in segment itself.
Of course I can change that and say: if end >= segment.length: endoffset  = -1 but I figured that this is a bug in the jsons so left it.

**Comment by sebastian-nehrdich** [comment]
OK I got it! I was interpreting this value as 'match until here not
including this character', that's why we got this mismatch. But I agree
that your understanding ('match until here including this character') makes
a bit more sense, so I changed the JSON accordingly. I am now starting to
upload the new files to the server! I have capped them now at max. 20
quotes to allow the performance to improve a bit.

**Comment by sebastian-nehrdich** [comment]
I have now fixed that (line is ending at 12 not at thirteen), but now for the root-segment "T31_T1599:10_1" no parallels are indicated at all! I wonder what could be the cause for this? (New files are now uploaded to the server).

**Comment by sebastian-nehrdich** [comment]
I have looked a little bit deeper into this issue and I am quite sure that we have some sort of bug in the display of the root-segment "T31_T1599:10_1"  and it's parallels, but I didn't get it yet, will investigate a bit more...

**Comment by sebastian-nehrdich** [comment]
Seems I found the error, trailing whitespace in the CBETA files is truly a mess! New JSON upload is coming today.

**Comment by sebastian-nehrdich** [comment]
Newest JSONS are all online now. I have fixed all bugs today that I could find. If anything remains, please let me know!

**Comment by ayya-vimala** [comment]
It looks okay to me so I will close this. But I don't have collection values for the Chinese collection filter yet so that just says `T01 T01`, etc. without a name. From the menu I also cannot get that data because neither fullname, author or dynasty seem to have anything to do with the category number itself. I will make a new issue for this.
