### ISSUE TITLE
Filtering does not work properly between collectoins

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#78]
#### Bug Description
Set a filter in one language will also use that filter in the other language but it won't update the filter options.

Best to cut filtering loose from general overlay and remove from redux store.

**Comment by ayya-vimala** [comment]
@sebastian-nehrdich This is a pretty big bug so I think needs to take precedence otherwise you never know what filters have been applied and it looks like there are no parallels while in fact there are.

**Comment by sebastian-nehrdich** [comment]
OK thank you for letting me know about this!

**Comment by ayya-vimala** [comment]
As you can see I've already fixed it and moved it into Review :-)
