### ISSUE TITLE
Feature request: Show length of parallel (text view + table view)

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#79]
@ayya-vimala I thought it would be nice if we display the length of each parallel, maybe next to the 'Probability' in the cell? Also the minimum length will vary from language to language. So we might have to adapt that accordingly. Finally it might be something like 4 for Skt and Tib and 6 for Chn (waiting for M's feedback now). And the description of the length-filter needs some adjustment - the filter is setting the min. length, not the max-length. :)

**Comment by sebastian-nehrdich** [comment]
I fixed this now in the small-changes branch. After merging I think we can close this (I trust you regarding the merge because you are the authority for the frontend-code of course!).

**Comment by ayya-vimala** [comment]
Ha ... if you don't mind I'd like to style it a little bit before closing. Will do this first thing. Only a small thing.

**Comment by sebastian-nehrdich** [comment]
Of course!

**Comment by ayya-vimala** [comment]
One more thing: I noticed you made some changes to the redux store. No harm there but I've disabled it to allow each page to have separate values. I left the code there for the time being in case we need it in the future.
