### ISSUE TITLE
Improvements for the filter by collection

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#80]
@ayya-vimala I had some discussion with Orna about the current state of the collection filters and there are some things we can improve on. 
First of all, next to an option to filter for a certain text, we should also add en option to include certain texts or categories. I think this would be easiest to implement with a second text box next to the one that we already have.
Regarding the dropdown-menus: I wonder if it is possible to have a menu where one can select or unselect various items at once. 
Ideally, the structure of such a menu should be like a tree. The main root of the tree (topmost item) should be 'show all results' - if that is checked, all results are shown. Then we have two branches, one is KG and the other one is TG. Here again when they are both selected, results from both collections are shown. When only K is selected, we only show items from K and so on. I think on the technical side that is easy to implement because we just need to filter for K or T. Then KG and TG in the dropdown menu again have all the categories as their children, which then again can be selected or not selected. 

While this sounds nice in theory, I didn't find a dedicated vaadin element. There is the multiselect combobox, which kind of does what we need but it doesn't support hierarchical data. So with all the many different categories we have I can imagine that this will quickly become a bit hard to manage. One could hack together a workaround based on paper-trees I think... Anyway, I will research a little bit further if there is some kind of ready-made solution for this.

**Comment by ayya-vimala** [comment]
One way you can filter for a certain text is simply to type the text number in the filter.
So you can filter on collection T06 for instance or just type T06TD4021E and then it filters for that. Or just even 4021 would do the trick unless there are more collections that have that number.

The main problem here again is the huge menu and no database. With a database this again will be much quicker and easier. if you have to load the whole menu again in a tree structure you recreate the same problem as we had with the menu and the slow loading of the site in the beginning, which you solved by just doing away with that and having a combo-box with the whole lot in it without the structure and lazy-loading (which I find vastly annoying and much too slow ... but the best we can do for now).

**Comment by ayya-vimala** [comment]
One thing I could do is make a new webcomponent for this, but it will take a bit of time. And that takes away from other things to do so it is important to set some priorities.

**Comment by ayya-vimala** [comment]
Or I can mess around today to get this one working:
https://github.com/tabalinas/multiselect-web-component

**Comment by ayya-vimala** [comment]
Okay, got this working. Will not upload for now because needs some styling and I want to talk to you first and show you to make sure I understood this part correctly and how it should behave.

**Comment by ayya-vimala** [comment]
Just one question on this. Before we had an 'and-and' policy on this but now it seems more logical to have it differently.
So for instance if I say that I want to filter on collection T06 and also on file "T054000E', that the filter gives you back all parallels instances where either T06 OR T054000E appears and not both (which would be none at all in this example).

**Comment by sebastian-nehrdich** [comment]
I vote for 'OR' because that makes more sense to me!
