### ISSUE TITLE
Menu disappears when window is not wide enough

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#82]
@ayya-vimala A friend who tested the site for me a bit reported that the top bar (Sanskrit Tibetan Chinese)  disappears when the window is not wide enough and then no options are shown. This can be a bit confusing - maybe we should at least display an error like 'window is not wide enough' or something like that so the user knows that something is wrong.

**Comment by ayya-vimala** [comment]
Yes, this is on purpose. The menu disappears when screens are less than 1000px wide. It says on the home page. The home page will show when there is no menu.

**Comment by sebastian-nehrdich** [comment]
OK got it! I agree that this makes sense & close this therefore.
