### ISSUE TITLE
Chinese collection labels

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#86]
The collection dropdown menu for filtering does not have any values for the Chinese collections so that needs to be added.

**Comment by sebastian-nehrdich** [comment]
https://github.com/ayya-vimala/pali-networks/blob/master/data-incoming/categories_ch.txt

if you need anything more please let me know!

**Comment by ayya-vimala** [comment]
I spoke too soon  and saw your issue 81 and you already did this! Well done. Will close this as it is double.
