### ISSUE TITLE
Filter by co-occurrence

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#94]
@ayya-vimala Just to warn you: I will add a filter today to filter by co-occurence as well (probably going to branch off and ask you later to merge). This is one way to get control over stock-phrases with high frequency and little meaning. This problem is actually pretty serious when it comes to the Chinese canon, where we frequently run into a similar situation as with Pāli. Let's see how well that will work.

**Comment by ayya-vimala** [comment]
Aahhh ... just spent ages just to get the current filters and other changes in on one line (at least on screens bigger than 1200px) so it does not take away too much space from the information below. I want to make sure that the numbers-table and text-view are still slightly managable in relation to space on the screen. I have a pretty large screen but not everybody does. Problem is that with every new filter the space for the actual text becomes smaller. I wonder if we should not move to a pop-up box for the settings at some point.

**Comment by sebastian-nehrdich** [comment]
I think we have to make a popup/foldable item at some point. I guess that
some more options will follow. I think an entire item for filters is more
than necessary!
I didn't yet have the time to look into adding the filter. If it is not too
much trouble for you, could you maybe add a filter for co-occurence? It
should be the just the same as the length-filter with a possible range from
0 to 30, mapped to the 'co-occ'-value in the json! At the same time, it
would also be nice to display the co-occ-value in the segments next to
Similarity and Length... I think these are small changes, maybe it's easier
if you make them and I will focus on fixing the data instead of forking off
a seperate branch at the moment.

**Comment by sebastian-nehrdich** [comment]
Sorry I made a mistake in my last post! The filter should not work
precisely as the length-filter, but it should rather work by cutting off
values that have a co-occurence score greater than x. So one should be able
to limit it from lets say 30 or mor (which would mean the filter is not
active) down to 10 or even just one (which is the lowest possible value).
Sorry for this!

**Comment by ayya-vimala** [comment]
So what is this exactly? What to put in the pop-up/hover explanation ?

**Comment by ayya-vimala** [comment]
Yes, I can do that tomorrow but I would like to have some files to test with and I guess those are not yet uploaded. The few I downloaded don't have that property in it.

**Comment by sebastian-nehrdich** [comment]
You could describe this as 'filter by number of co-occurences'.  The idea
here is that one can filter out parallels with more then X co-occurences so
we can get rid of loop-quotations like 'evam me suttam'. M made the very
important point that we have to address this issue if we want the tool to
be of any use for scientific purposes and I agree with that. I cannot yet
say say if this filter is going to be serve that function in practice, but
let's see!
I will upload you a few examples with the new value ('co-occ') now!

**Comment by ayya-vimala** [comment]
I've done this but before uploading will put them into a separate dropdown for all those sliders so as to safe space.

**Comment by sebastian-nehrdich** [comment]
yes great, thank you!

**Comment by ayya-vimala** [comment]
I've done this and pushed it but not uploaded to main site.

**Comment by sebastian-nehrdich** [comment]
Great, thank you for this! Will check it out later, now I am taking a break
and go out for a while...

**Comment by sebastian-nehrdich** [comment]
Looks & works great, I also like the layout with the dropdown box for the menus very much now. Good solution!

**Comment by sebastian-nehrdich** [comment]
By the way, I think it would be nice to also display the co-occurrence-value in the parallel-box middle column next to probability and length!

**Comment by ayya-vimala** [comment]
Sure. will do. Just working on the routing at the moment. Something is not working as it should ... :-(

**Comment by sebastian-nehrdich** [comment]
could we change the default value to max (-> filter is not active)? I think this should work better...

**Comment by sebastian-nehrdich** [comment]
changed the code so now 30 means 30 or more.

**Comment by sebastian-nehrdich** [comment]
We just need to add to the description '30 means 30 or more', apart from this I think this is working very well. I have done some tests on some very highly referenced  Chinese texts and this really helps to reduce the noisy of unwanted stock phrases.
