### ISSUE TITLE
Add prettier formatter to standardise JavaScript code formatting

### ISSUE THREAD

**Issue by TrebuhD** [ayya-vimala/pali-networks#96]
Prettier (https://prettier.io/) can help us maintain a uniform code style by formatting our code automatically when committing. This ticket is to add that capability.

TODO:
- Add prettier package to project
- Add Githook to run prettier automatically on commit

**Comment by ayya-vimala** [comment]
Sounds great. I've installed it and will try it out.

**Comment by sebastian-nehrdich** [comment]
Good idea to use this. My emacs js2 seems to have quite a strong opinion on
whitespace and it frequently disagrees with the formatting of Vimalas files
so I am very sorry for introducing this mess!

**Comment by ayya-vimala** [comment]
@TrebuhD What hook do you use? Does not seem to like the rev in this:

> repo: https://github.com/prettier
>   rev: v1.18.1
>   hooks:
>     - id: prettier

**Comment by TrebuhD** [comment]
@ayya-vimala it will be added locally to the repo, no need to install anything to your system :). I can add it now if you'd like.

**Comment by ayya-vimala** [comment]
I added a .pre-commit-config.yaml to the highlighting-branch but you can remove that if not needed.

**Comment by TrebuhD** [comment]
I think this file is for python projects. In any case, let's try to use the standard [GitHub flow](https://guides.github.com/introduction/flow/) here by creating a separate branch with just this feature. This way we can easily track code changes inside pull requests.
