### ISSUE TITLE
Probability cutoff does not change the colors

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#97]
#### Bug Description
I'm not sure if this is meant to be this way but changes in the probability cutoff do not change the colors of the segments in text view left side.

#### Steps To Reproduce:

1. Go to Tibetan -> T06TD4021E
2. See the colors of the first colored segment with default cutoff at 50%. 
3. Change the cutoff with the slider
4. Then see that when the slider comes above 57% it becomes black, but below 40% another parallel should be added and therefore the color should change.

It seems to work with parlength and co-occ.
 
#### Expected behaviour
Would expect the colors to change based on the number of parallels that match with current probability filter setting. Or at least have some indication that there is a second parallel there, which I cannot see unless I change the probability filter settings.

Further down it seems to work with the probability settings but not the first one.

If this is meant to be with regards to the colors, then maybe we should change the text in the middle column to read differently. It now reads:

> There are 1 parallel segments found for the selected segment with the current filters.

Maybe this should become: 

> There are 2 parallel segments found for the selected segment, of which 1 with the current filters.

Or something like that.

**Comment by sebastian-nehrdich** [comment]
I cannot reproduce this. When I slide the threshold below 40%, the other
parallel appears and the color changes accordingly (as expected). It's true
that the difference between blue and violet might not be very strong but it
certainly works! I checked this also with a couple of other files and cases
and it seems to be OK as far as I can tell.

**Comment by ayya-vimala** [comment]
I really cannot see any difference on my screen. :-(
But if you say it works I believe you. 
How about adding a message anyway to let people know the total number there without filters? up to you, otherwise please close this issue.

**Comment by sebastian-nehrdich** [comment]
Maybe it is an issue with the color not being very different from each
other, I don't know!  I wonder if it makes sense to so the colorcodes a bit
more progressively. So the different between 1-2 and 2-3 should be stronger
than between 7-8 and 8-9...  At the moment this is linear.

**Comment by ayya-vimala** [comment]
You can use RGB numbers and add a value to each of the 3 parts of that for every parallel added.

**Comment by sebastian-nehrdich** [comment]
Could you maybe check the color value for the span element of the passage
where you have the impression that it is not changing accordingly in the
inspector?
For one quote it should be: style="color:hsl(252, 100%, 50%)"
for two quotes it should be: style="color:hsl(276, 100%, 50%)"
If this is indeed not as it should be, then we have a problem! Also you
could try to clear browser cache, reload everything etc. - maybe some
outdated data is still cached.

**Comment by ayya-vimala** [comment]
It changes, but from 252 to 264. The difference between those is so small that for something like text it is hardly visible. 

I manually changed two words next to each other to 252 and 276 resp and the difference between those is visible, but barely.

**Comment by sebastian-nehrdich** [comment]
This is good to know! So the problem has nothing to do with the code itself
but with the chosen coloring scheme which  doesn't show very clear
differences.
I see when I find time to rework this...

**Comment by sebastian-nehrdich** [comment]
@ayya-vimala I have now reworked the highlighting and the css in order to make differences a bit more distinct. It's already in the new branch on github and on the main server. 
Also I updated the Tibetan files once again and now a few more bugs regarding the boundaries of the matches got fixed. It is not yet 100% perfect, occasionally a word is missed or highlighted wrongly, but generally it's OK I think. Also I changed the scoring strategy from cosine similarity to jaro-winkler which correlates a bit better with human judgement I think. Cosine similairty has the tendency to converge towards 1 the longer the passages get, so it's really not a good metric for comparing texts of variable length...

**Comment by ayya-vimala** [comment]
You might have to check after merge. I had to undo some things because the code was such a mess it became impossible to see what was what. I think the highlighting color changed back too but that will be a small change.
For some strange reason all the elements in the menu started appearing under each other and the co-occurances in a different place too, which resulted in no more space for some of the other elements so I changed that all back too.

**Comment by sebastian-nehrdich** [comment]
I fixed the colors again, looks generally OK to me as it is right now... 
Possibly we can cloes this issue (maybe open a new one regarding improvements on the CSS) since the CSS layout has nothing to do with the probability filter.
